### ISSUE TITLE
gix fetch return error 'Cannot find a remote for unborn branch' with bare repo

### ISSUE THREAD

**Issue by eatradish** [Byron/gitoxide#1003]
### Current behavior 😯

After some steps (see "Steps to reproduce"), `gix` returns the error:

```
$ gix fetch origin +refs/heads/*:refs/heads/*
Error: Cannot find a remote for unborn branch
```

with `gitoxide v0.29.0`

### Expected behavior 🤔

`git` success to run:

```
$ git fetch origin +refs/heads/*:refs/heads/*
from https://github.com/AOSC-Dev/oma
 * [new branch]          cratify-oma -> cratify-oma
$ echo $?
0
```

### Steps to reproduce 🕹

```
gix clone --bare https://github.com/AOSC-Dev/oma oma-bare
mkdir oma-not-bare
cd oma-not-bare
git init
git --git-dir ../oma-bare --work-tree . checkout -f e8f56b5
cd ../oma-bare
gix fetch origin +refs/heads/*:refs/heads/*
```

**Comment by Byron** [comment]
Thanks for reporting!

`gix` ≠ `git`, and the correct way of specifying the remote explicitly is `gix fetch -r origin`. If that's done, it works as it won't fail to try to deduce the remote from `HEAD` which isn't a symbolic reference anymore, i.e. detached.

However, `git fetch` will work in such a situation, whereas `gix fetch` will still complain about the lack of remote. It appears `git` will fetch the only stored remote as long as there is only one, or do nothing without erroring otherwise. I think `gix` can do the same but with proper error handling.

**Comment by Byron** [comment]
Closing as this is fixed in `main`. Please let me know if something else shows up.
Thanks a lot.
