### ISSUE TITLE
Support aliases

### ISSUE THREAD

**Issue by dreamlax** [Byron/gitoxide#1253]
### Summary 💡

If git config contains aliases like this:

```
[alias]
    s = status
```

Running `git s` will then run `git status`.

### Motivation 🔦

This is just QoL - I think it is not of any real priority.

**Comment by dreamlax** [comment]
I know `clap` supports compile-time aliases for subcommands, but I'm not sure if these aliases can be supplied at runtime. Although, I guess this gets tricky if you need to also handle `-c`, for example, `git -c alias.b=status b` works but I can't think this would be a real-world use case.

**Comment by Byron** [comment]
Thanks for bringing this up!

I don't, however, see how this is applicable to a library, as integrating alias-support into a command-line application depends on factors outside of its control.

One can already read the git configuration values and with that one would be able to handle aliases correctly, but I don't think there is a way to make this easier than it already is.

`gix`, the CLI program, isn't applicable for this either as it's not trying to be a `git` clone. Since it's a developer tool, I don't think it needs aliases either, particularly not those that are also used by `git`.

Thanks for your understanding.
