### ISSUE TITLE
gix-transport 0.41.3 has issues

### ISSUE THREAD

**Issue by Jake-Shadle** [Byron/gitoxide#1328]
### Current behavior 😯

```
[ERROR] failed to fetch advisory database https://github.com/rustsec/advisory-db: An IO error occurred when talking to the server: error sending request for url (https://github.com/rustsec/advisory-db/info/refs?service=git-upload-pack): client error (Connect)
```

See https://github.com/EmbarkStudios/cargo-deny/issues/641 for the error that is being seen. Basically, this caused by either gix-transport 0.41.3, or one of the HTTP libs it depends on that was also updated

```
    Updating gix-transport v0.41.2 -> v0.41.3
      Adding h2 v0.4.3
      Adding http v1.1.0
      Adding http-body v1.0.0
      Adding http-body-util v0.1.1
      Adding hyper v1.2.0
      Adding hyper-util v0.1.3
      Adding pin-project v1.1.5
      Adding pin-project-internal v1.1.5
      Adding reqwest v0.12.1
      Adding tower v0.4.13
      Adding tower-layer v0.3.2
```

If I downgrade to gix-transport 0.41.2, which also downgrades various HTTP libs, cargo-deny works as intended.

### Expected behavior 🤔

The requests succeed as they do with 0.41.2.

### Steps to reproduce 🕹

1. `cargo install --version 0.14.19 cargo-deny`
2. `cargo deny check advisories` in a directory with a Cargo.toml

**Comment by Byron** [comment]
Thanks for reporting! This change was introduced as non-breaking in #1327, but it was only non-breaking if `gix` was also using the latest version of `reqwest`. Otherwise, I could locally observe connection issues when trying any HTTPS request.

When installing `cargo-deny` as specified, I noticed that it uses `gix-transport v0.41.3`, but not the latest released `gix v0.61.1`, but `gix v0.61.0`.

Looking into this, I also discovered that `gix v0.60` would also be able to pull in `gix-transport v0.41.3`, and probably suffer from the same issues.

To fix this, I yanked `gix v0.61.1` and `gix-transport v0.41.3`, and could validate that the steps to reproduce listed here don't reproduce the issue anymore.
Further, I created a commit which now marks this as breaking change, which will cause breaking releases down the dependency chain automatically, including `gix`, so I can't accidentally publish such a combination again.

* CC @obi1kenobi, even though this breakage is really special as I detected it locally, but only at runtime. You might be interested as an issue 'on the fringes of detectability' though. 
* CC @NobodyXu who originally asked for a release of this seemingly non-breaking update, and who know would have to wait for `gix v0.62` to be released next month (there has been a lot of release-churn lately). Thanks for your understanding.

**Comment by Byron** [comment]
I believe the issue is resolved, but I will leave it to @Jake-Shadle to double-check and close.

**Comment by amousset** [comment]
This indeed works for `cargo-audit` and `cargo-deny@0.14.19` in my tests, thanks for the quick fix!

**Comment by NobodyXu** [comment]
Thanks for informing me of this, I'm totally ok with this.

I have a question though, is it not possible to move `reqwest` (and possibly `curl`) completely to `gix-transport`?

It sounds strange that it is pulled in `gix-transport` then `gix`.

Is it just for the features?

If so maybe it's a good idea to declare the features in `gix-transport` then re-export to `gix`?

**Comment by Byron** [comment]
Indeed, `gix` only has the `reqwest` dependency for the purpose of configuring its features. And in this particular case where there is a breaking change in `reqwest` (or `curl`) *and* the crate itself is 'made' in a certain way, we may see this effect. It feels like circumstance-meets-circumstance-meets-circumstance, and all are quite unlikely, but when they line up, it's game over 😅.

It's actually a great idea to simply forward the features in `gix-transport`, for `reqwest` and `curl` for good measure, in order to prevent this from ever happening again.

Feature-forwarding was always what I tried to avoid as it doesn't scale well at all, but here I don't think it would make a big difference and, given the danger that was uncovered now, it must be fixed.

@NobodyXu , would you mind creating a quick PR for `reqwest`? I would probably add `curl` forwarding myself then - that way I definitely won't forget.

**Comment by NobodyXu** [comment]
Created #1329
