### ISSUE TITLE
unread field warnings on nightly

### ISSUE THREAD

**Issue by joshtriplett** [Byron/gitoxide#1330]
A build with nightly Rust gives a bunch of "fields `x` and `y` are never read" warnings. Wanted to give a heads up on those before they hit stable.

**Comment by Byron** [comment]
Thanks for letting me know!

I have addressed the issue in the linked commit. Once (in `gix-index`) the warning was legit and stems from not actually using all extension data that is read (and it's not completely written back either.

However, another warning `gitoxide-core` was a little different as the code is explicitly writing a debug version of the top-level struct in order to avoid having to implement `Display`. `Debug` doesn't count anymore as use, which is understandable, and the whole sub-command is kind of a debugging tool anyway. In this case, the best choice seemed to be to suppress the warning.
