### ISSUE TITLE
Panic receiving pack if fetch interrupted

### ISSUE THREAD

**Issue by LuaKT** [Byron/gitoxide#1352]
### Current behavior 😯

Hi, I'm seeing a very occasional panic when fetching a repository and I interrupt it part way through receiving.
```
thread '<unnamed>' panicked at /home/lua/.cargo/git/checkouts/gitoxide-9add020dee14babf/035ca54/gix/src/remote/connection/fetch/receive_pack.rs:290:70:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "interrupted by user" }
```
Unwrap is called here https://github.com/Byron/gitoxide/blob/v0.35.0/gix/src/remote/connection/fetch/receive_pack.rs#L290, is there any need to unwrap here or can errors just be ignored?

Thanks!

**Comment by Byron** [comment]
Thanks for reporting! It's fixed in the linked branch, using `?` was intended here. Unwraps should never be used in production code, and if panics aren't possible, then `.expect("why this can't happen")` should be used instead. Thus, I don't know how that `.unwrap()` snuck in there, sorry for that :/.

**Comment by LuaKT** [comment]
Thanks for the quick fix!
