### ISSUE TITLE
Use Conventional Commits and calculate version number for releases

### ISSUE THREAD

**Issue by sschuberth** [Byron/gitoxide#1399]
I propose to start adopting [Conventional Commits](https://www.conventionalcommits.org/) for commit messages plus one of the following tools to calculate the [Semantic Version](https://semver.org/) and generate notes for releases automatically:

- https://github.com/orhun/git-cliff
- https://github.com/cocogitto/cocogitto
- https://github.com/convco/convco

**Comment by Byron** [comment]
Maybe it's the fact that conventional commits are used sparingly which gives the impression that they are not used at all. However, when used, [`cargo smart-release`](https://github.com/Byron/cargo-smart-release) will put them into changelogs automatically, distributed in a file, in a tag, and on GitHub releases.

I am sure there are various ways in which these can be improved, but such suggestions would be a better fit in the repository linked above.

**Comment by sschuberth** [comment]
> Maybe it's the fact that conventional commits are used sparingly which gives the impression that they are not used at all.

If you're trying to say that this project already uses CC, then yes, that's absolutely not apparent. As a new contributor to an OSS project I usually check the last few commits to learn about the commit conventions, and well, there seemed to be no conventions / common style at all.

> However, when used, [cargo smart-release](https://github.com/Byron/cargo-smart-release) will put them into changelogs automatically, distributed in a file, in a tag, and on GitHub releases.

Ok, yet another tool for making CC releases, good.

> I am sure there are various ways in which these can be improved, but such suggestions would be a better fit in the repository linked above.

I believe you misunderstood the main purpose of this issue. Which is to establish that *every* commit has to follow CC, in order to reliably calculate the version for releases, and not disregard something that is not using CC.

**Comment by Byron** [comment]
> I believe you misunderstood the main purpose of this issue. Which is to establish that _every_ commit has to follow CC, in order to reliably calculate the version for releases, and not disregard something that is not using CC.

That's absolutely correct, I misunderstood the purpose.

The purpose of CC here is to mark what should go into the *prominent part* changelog, and whether something is breaking or not. Not everything should go into the changelog to reduce noise. Since every commit is still visible in the changelog, there is nothing lost for those who want to see it all either.

Thus, I am not closing it as presumably done, but as not planned this time.
Thanks for your understanding.

**Comment by sschuberth** [comment]
> Not everything should go into the changelog to reduce noise.

I sympathize with that.

However, taking care for this is in the responsibility of the CC tool that you use to generate your release notes / changelog; it's not an argument for not using CC for commits that should not appear there.

For example, `chore`-type commits could be left out. Or in fact any custom type that you introduce (see [point 14 of the specification](https://www.conventionalcommits.org/en/v1.0.0/#specification), and you should actually make good use of that, even beyond [the types that the Angular project uses](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type) if required).

**Comment by Byron** [comment]
I see! That's definitely something that `cargo smart-release` would have to add support for then, as right now it's designed in the way described.

Personally, I would never want to bother contributors with how they write their commit messages, unless I have to because it's a breaking change which must be signalled. So being flexible has been very practical especially compared to the times when I had to ask for this kind of change.

In my ideal world, every commit message is as descriptive as it is in Git itself, while having tooling that makes it really easy to actually see those (like Code Lens, but with the ability to skip over commits easily). And of course, it's reasonably easy to generate a changelog for that, but maybe manual curation is the way to go here anyway to get the highest possible quality.

Right now, the quality of the changelogs here is 'better than nothing' but far and away from stars like Bevy or even Tokio.
