### ISSUE TITLE
docs.rs hasn't picked up git-repository v0.6.0

### ISSUE THREAD

**Issue by jeffparsons** [Byron/gitoxide#148]
No idea why. Not sure if it affects other gitoxide crates. Just thought I'd mention it in case other people get confused between the mismatch in "latest" docs vs. latest released crate versions.

**Comment by jeffparsons** [comment]
Ah, I think it's because it depends on git-diff v0.4, which isn't published. I'm not sure why that was even possible! o_0

**Comment by Byron** [comment]
Sorry for the hassle, it's very possible that docs are out-of-date right now or fail to build because I was working with a 'hacked' version of `cargo release` for a while that would not verify the package before publishing. This was based on the idea that I could manage to publish crates in the correct order but that definitely didn't pan out as planned.

Next time I am releasing this should be fixed, in the meantime building the docs from `main` seems to be the only workaround.

**Comment by Byron** [comment]
This should be fixed now with git-repository 0.7. Please take a look.
