### ISSUE TITLE
edge-case: symref targets in namespaced repos

### ISSUE THREAD

**Issue by kim** [Byron/gitoxide#205]
This is more of a heads-up:

`git-protocol` enables the `symrefs` capability for `ls-refs` by default. If the remote repo is actually a namespace, and contains refs which point to targets _outside_ that namespace, `upload-pack` advertises `symref-target:(null)`. For example:

Given:

```
refs/namespaces/A/refs/heads/main      # deafbeef
refs/namespaces/B/refs/heads/main-of-a # ref: refs/namespaces/A/refs/heads/main
```

`ls-refs` in the context of `B` gives:

```
upload-pack> deafbeef refs/heads/main-of-a symref-target:(null)
```

That makes sense, because namespaces are supposed to be opaque to clients, and so what refs exist outside the namespace should not be revealed.

However, when parsing into the `Ref` type, `git-protocol` takes the value of `symref-target` verbatim, so we get:

```rust
Ref::Symbolic {
    path: "refs/heads/main-of-a",
    target: "(null)",
    object: Sha1(deafbeef),
}
```

Within `gitoxide`, this is safe, because the target is validated when constructing a `RefEdit` (if we were to mirror the remote refs tree after a fetch). It may still be more saferer if `target` was of type `Option<BString>`, and "(null)" parsed as `None`, for example when a library user is handing that value out to other tools without validating it first.

**Comment by Byron** [comment]
I call that an interesting find! When digging through canonical git source for a moment I found the code producing this pattern "(null)" hard to find, maybe it's because it's really just a side-effect of them [not checking for null](https://github.com/git/git/blob/master/ls-refs.c#L97:L98) and [vsprintf](https://github.com/git/git/blob/master/strbuf.c#L263:L263) doing this by itself.  Now I tried to find information on what this function is supposed to do when NULL is encountered, but it doesn't look like this behaviour is well defined.

Handling it on the receiver seems like the right thing to do, but I'd rather entirely filter out such references as to not force everyone to deal with `Option<BString>` at least while this behaviour isn't defined.

In the light of the information presented here, what's your take on it?

**Comment by kim** [comment]
> Handling it on the receiver seems like the right thing to do, but I'd rather entirely filter out such references as to not force everyone to deal with Option<BString> at least while this behaviour isn't defined.

Well that would break most of my code :D 

I’d rather turn off the symrefs capability, because it is not that useful anyway.

**Comment by Byron** [comment]
Sorry, edits don't trigger notifications, I basically did a 180 on that initial suggestion, going with `Option<…>` instead. Symrefs shall live 😅.

**Comment by Byron** [comment]
Please take another look, the fix is in main and `target` is now `Option<BString>`. While working on this I noticed that the object pointed to can apparently still be resolved which seems odd. Or can't it? After all, it's leaking information from another namespace.

**Comment by kim** [comment]
> `target` is now `Option<BString>`

Thanks!


> While working on this I noticed that the object pointed to can apparently
> still be resolved which seems odd.

[Yes yes](https://git-scm.com/docs/gitnamespaces#_security).


There are hints that Junio might not like git-namespaces that much, and so the
feature is treated a bit less-than-first-class. I think git clients only really
consider the HEAD symref, and only when cloning, so I'll see if I can break
their tests by pointing HEAD to a different namespace.

**Comment by Byron** [comment]
> [Yes yes](https://git-scm.com/docs/gitnamespaces#_security).

Seems the world is riddled with bugs and rescue is impossible. When markdown renderers can't perform basic tasks anymore, all is clearly lost 🤦‍♂️.

> […] so I'll see if I can break
their tests by pointing HEAD to a different namespace.

…because there is only one thing Junio likes _even_ less: broken tests! I don't _ever_ want you as my enemy 😅.

**Comment by kim** [comment]
> I think git clients only really consider the HEAD symref, and only when
> cloning, so I'll see if I can break their tests by pointing HEAD to a
> different namespace.

I played around with this (t5509), and I think git is basically fine with junk as the value of `symref-target`. The only remote symref git cares about is HEAD, and only when cloning. If it sees a `symref-target`, it will try to match the value against the other refs which were advertised in the response to `ls-refs`.

Obviously, "(null)" will never match, because that is not a valid refname (if the remote would nevertheless advertise a "(null)" ref, `update_remote_refs` would fail, because that validates refnames).

When this happens, the working tree will be checked out in "detached HEAD" mode, which is the same effect as if `symref-target` was not present at all.

So, even though the string "(null)" might be accidental, there is little incentive to change this in upstream git, except for saving a miniscule amount of bytes on the wire.

I suppose the most correct way to deal with this would be to type refnames in `Ref` as `FullName`, implying that they are validated upon reception. Whether it is preferable to perform validation at the edge of the system, or equate "low level" with "less strongly typed" is a philosophical question of course.

I realise, however, that a `Ref::Symbolic` with an optional `target` does not actually make a lot of sense -- I was thinking "what if I could explicitly turn of `symrefs`", but in that case a symref is indistinguishable from a direct ref.

Thoughts?

**Comment by Byron** [comment]
Great detective work, even though I would have hoped for a harder crash of sorts.

To sum it up, when git encounters `(null)` as symref-target during a clone it ends up with a detached head as it can't find the ref `HEAD` allegedly points to in the list of advertised refs. It's probably also the best it can do, even though once again it accidentally ends up there.

> I suppose the most correct way to deal with this would be to type refnames in `Ref` as `FullName`, implying that they are validated upon reception. Whether it is preferable to perform validation at the edge of the system, or equate "low level" with "less strongly typed" is a philosophical question of course.

I hope it doesn't have to be philosophical at all, it's _(hopefully)_ more about expectations one would have in a system. When talking to the server we wouldn't trust anything it tells us. But I'd argue that people operating on this level at least want to know what it has to say and make decisions on their own. Hence I would not want to degenerate information, nor would I want to perform additional validation beyond what the protocol dictates. Currently for symref targets we have `Option<BString>`, which tells us that there might be no target at all in edge-cases, and that they might not even be valid ref names. And I think it's fair dealing with that and make choices actively while possibly providing more information to the user or let them decide even. Maybe broken symrefs are a no-go and such users don't want any of that checked out even, whereas others might want to salvage what they can but are aware the head might be detached after clone.

Does that make `git-protocol` less strongly typed? Technically, yes, but I think it uses the typesystem to the extend possible to represent what the server can legally say, even if it's garbage within the confines of the protocol, which helps you (and forces you) to deal with it.

Thus, I wouldn't take any additional action here.

**Comment by Byron** [comment]
Or maybe, described differently: I think the current setup is adequate as it allows clients to make their own conscious decisions on how to handle this situation, and that's worth the added complexity which is inherent to the `git` now that we know about it. 

I can imagine, one day, that `git-repository` supports clones and has a bunch of options, one of them controlling how to deal with this edge-case. Is it OK to have a detached HEAD, or not, and it's a choice somebody actively makes (or not if there is a sane default, which probably is aborting such a clone early).

**Comment by kim** [comment]
> Hence I would not want to degenerate information, nor would I want to perform additional validation beyond what the protocol dictates.

Fair.

> Thus, I wouldn't take any additional action here.

Except maybe da68bfb8104ecf58e73e3f99d87f81c90712a2ca was a little rushed?

We found "(null)" to be an accidental value, and I would want gitoxide to encode as little as possible of git's quirks. So, as per "what the protocol dictates", I think the previous behaviour was actually correct: of there is a `symref-target`, the remote advertised a `Ref::Symbolic`, whether or not the target is actually valid. The only possible fix on git's side would be to omit `symref-target` if it turns out to be NULL after stripping the namespace. In which case we would parse it as `Ref::Direct`.

**Comment by kim** [comment]
> Is it OK to have a detached HEAD, or not, and it's a choice somebody actively makes (or not if there is a sane default, which probably is aborting such a clone early).

Oh absolutely, think of `git clone --mirror`. It is just that git's error message makes you think something really bad happened, when it's just that git couldn't figure out a default branch to check out. Instead of evoking pictures of walking Störtebekers, git could also politely ask if you want to pick a branch.

**Comment by Byron** [comment]
> Except maybe da68bfb was a little rushed?

Ah, you mean because it degenerates information? To me it's more like 'translating' it into something more than garbage, it's like when parents tell you what their baby is talking about even though it's utter nonsense 😅. Even as future oddnesses are discovered I'd think it's a service of `git-protocol` to make translate them into decently documented types so others will have to make decent choices based on that, rather than validation failing somewhere down the road and people realize they have been talking to a baby the hard way.

> We found "(null)" to be an accidental value, and I would want gitoxide to encode as little as possible of git's quirks. So, as per "what the protocol dictates", I think the previous behaviour was actually correct: of there is a `symref-target`, the remote advertised a `Ref::Symbolic`, whether or not the target is actually valid. The only possible fix on git's side would be to omit `symref-target` if it turns out to be NULL after stripping the namespace. In which case we would parse it as `Ref::Direct`.

My paragraph above was clearly written before reading this one :D. If this was git's only option, I am in perfect agreement. Thinking about it differently, symref support isn't a requirement and those who ignore it would have a detached head and deal with it. Thinking about `git-repository`, there could still be an option that requires HEADs to be attached.

Assuming git wouldn't pick its other option and abort when encountering a symref in another namespace, the next best fix is to not send such value at all. And… this means da68bfb should be changed so that we interpret broken symrefs as direct refs.

Do you think that's the action to take?

**Comment by Byron** [comment]
I took the liberty and implemented it like this, and it's much nicer on the client side.
It was interesting to so how easy it is to create and change an opinion as the matter is viewed from different angles and as new information becomes available.

**Comment by kim** [comment]
> > Except maybe da68bfb was a little rushed?
>
> Ah, you mean because it degenerates information?

Yeah, now you're half-way between validating that the remote advertises well-formed refs (which the protocol kind-of implies, but doesn't state explicitly), and passing through the wire data.

If I care about well-formed refs _before_ attempting to create them locally, I would probably just define

    enum WellFormedRef {
        Direct {
            path: FullName,
        // etc
        },
        // etc
    }

and provide `TryInto<WellFormedRef> for Ref`.

> Assuming git wouldn't pick its other option and abort when encountering a symref in another namespace, the next best fix is to not send such value at all.

Well, no: the peeled target of symrefs is always sent, `symref-target` is just a hint so the local end could re-create it as a symref, too, instead of direct. It would certainly not be correct to omit refs just because their symbolic representation cannot be recreated on the receiving end. Sure HEAD is special, and ls-refs could choose to omit it in this case in order to not confuse clone, but otherwise it is perfectly valid to use symrefs just like symlinks.

> And… this means da68bfb should be changed so that we interpret broken symrefs as direct refs.
>
> Do you think that's the action to take?

I think it should not look at the values at all, just like before, unless requested. Which can also be done after having received the advertisement, but before attempting to update the local tips, as a convenience (like described above).

**Comment by Byron** [comment]
> I think it should not look at the values at all, just like before, unless requested.

I think the highlight here is: _unless requested_, it's a requirement I don't grok. The current implementation turns something that would be surprising, '(null)' into something that git would have to send if it would check for null pointers. And under the assumption that all vsprints in the world turn `NULL` into `(null)` the fix that `git-protocol` applies will always do the right thing. The alternative is that people now have to be aware that '(null)' could be present, which really is the only case we know when symref targets are not well formed.

I hope the point I am trying to make is coming across as: users of `git-protocol` have know less of gits quirks to interact with it successfully and without surprises. I mean, it might be surprising that `HEAD` is reported as direct ref, but it's something code has to deal with either way.

>  Which can also be done after having received the advertisement, but before attempting to update the local tips, as a convenience (like described above).

'(null)' would be caught as invalid ref name, but that error is created in `git-ref`, and not in the client code that tries to pull. That could would then have to check for this case in order to handle it well, which is harder than differentiating direct and symbolic refs. So not handling '(null)' even though `git-protocol` is in a good position to do that seems like pushing the burden down the chain making it harder for everyone.

The code you would write with `git-protocol` as it is right now, wouldn't that be simpler, too? Or is there anything gained from handling '(null)' on your end? And of course, this is not supposed to become fully fledged validation, it's intended solely to gloss over edge-cases like these that nobody would expect really.

Thanks for bearing with me by the way, I see how this thread is ping-ponging from one side to the other, but I have the feeling it stabilises around a decent solution after having explored some extremes 😅.

**Comment by kim** [comment]
On Fri, 24 Sep 2021 03:12:30 -0700 Sebastian Thiel ***@***.***> wrote:

> The current implementation turns something that would be surprising, '(null)' into something that git would have to send if it would check for null pointers.

Well, yes and no. If git would check for null pointers, it would have to omit "symref-target", because there is no way (apart from "(null)") to represent "I don't know, or won't tell you". It would _not_ have to omit `sha SP refname`, not even if HEAD is not a symref.

In fact, if you clone from a repository where HEAD is a direct ref (eg. because it's not actually a bare repo, and you're in the middle of doing something involving HEAD), git clone will ignore it and try to guess the default branch ("master" seems to be preferred over "main", which is preferred over "trunk" in my limited testing). Funnily enough, it will not try if there is no HEAD at all in the ls-refs response (which can happen with namespaced repos), and instead give you the störtebeker. That's because HEAD is deeply magical.

So my points are:

- `Ref::Symbolic { target: None, .. }` is actually meaningless, it's a direct ref
- "(null)" is just a special case of an invalid target, ".lol" is not a valid refname either

 So turning "(null)" into `None` but ".lol" into `Some(".lol")` is rather arbitrary, as neither can be used to re-create the ref locally. Who says the remote can respond in only one invalid way?

I would personally not want to carry the baggage of checking for one special case, but ignoring others, but if you do, I think mapping to `Ref::Direct` is the least surprising.

**Comment by Byron** [comment]
> Well, yes and no. If git would check for null pointers, it would have to omit "symref-target", because there is no way (apart from "(null)") to represent "I don't know, or won't tell you". It would _not_ have to omit `sha SP refname`, not even if HEAD is not a symref.

Right, and sorry for the strange phrasing of "git would have to send if it would check for null pointers" - it's exactly that, it would have to make it a direct ref, `NULL` can't be represented in the current format.

> In fact, if you clone from a repository where HEAD is a direct ref (eg. because it's not actually a bare repo, and you're in the middle of doing something involving HEAD), git clone will ignore it and try to guess the default branch ("master" seems to be preferred over "main", which is preferred over "trunk" in my limited testing). Funnily enough, it will not try if there is no HEAD at all in the ls-refs response (which can happen with namespaced repos), and instead give you the störtebeker. That's because HEAD is deeply magical.

I find the logic of git trying really hard to find a matching ref to point HEAD to fascinating, thanks for sharing :). At some point, a sorry someone might have to implement something like it.

>  So turning "(null)" into `None` but ".lol" into `Some(".lol")` is rather arbitrary, as neither can be used to re-create the ref locally. Who says the remote can respond in only one invalid way?
> I would personally not want to carry the baggage of checking for one special case, but ignoring others, but if you do, I think mapping to `Ref::Direct` is the least surprising.

Thanks so much, this is what I wanted to hear to know that I am not entirely on the wrong track here. c77bd7a01820110154f2c66cd954c1ccfff173c1 is implementing exactly this, it turns `(null)` symrefs into direct refs.
