### ISSUE TITLE
Contributing to pack-send

### ISSUE THREAD

**Issue by GaurangTandon** [Byron/gitoxide#41]
Hi, I wish to contribute to a feature in this repo, and pack-send sounds straightforward. Should I try to work on this if it's already not taken?

**Comment by Byron** [comment]
Hi! Such a contribution would certainly be much appreciated as the work block is definitely ready to go.

There has been progress already in `git-protocol` and `git-transport` already to greatly facilitate sending the pack over the wire. However, pack generation hasn't been touched yet even though the APIs exist to traverse objects and build it from there.

From my point of view it seems like it will take quite some effort to get done though even if the pack is not creating deltified objects at first.

Please let me know if there is anything specific I can help you with. Otherwise I recommend creating a draft PR so communication can happen there most efficiently.

Thanks and cheers

**Comment by GaurangTandon** [comment]
Great, I'll attempt to study the relevant gitoxide codebase, and open a pull request as soon as I have some idea of the implementation.

Cheers!
