### ISSUE TITLE
`cargo-smart-release` changelog generates broken (invalid) links when using ssh remote

### ISSUE THREAD

**Issue by mattcl** [Byron/gitoxide#512]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

I've been using `cargo-smart-release` for months now and just noticed today that the links to commits in the generated changelog are invalid. See https://raw.githubusercontent.com/mattcl/confpiler/13c07d1003754ef0bfbccc350ffa7ac99b066d3d/confpiler_cli/CHANGELOG.md

Specifically, the generated host is `https://github.comgit//` note the "git" suffix and the extra slash. 

That repo has the following remote configuration on my local machine: 
```
$ git remote -v
origin	git@github.com:mattcl/confpiler.git (fetch)
origin	git@github.com:mattcl/confpiler.git (push)
```
I suspect this line to be the culprit, but I have to admit I've only briefly dug through the code. https://github.com/Byron/gitoxide/blob/239cb8a7c25f89ad087f201982585ab4c904c77b/cargo-smart-release/src/changelog/write.rs#L70

It would seem that the `user` in that case is going to be `git`.

Checking my other projects using smart release, they all exhibit this problem in their changelogs.

I can confirm that switching the remote url to use https instead of git@... generates a changelog with the correct commit links.

A quick search on github yields other repos with changelogs exhibiting the same issue. Here's an example https://raw.githubusercontent.com/saskenuba/yapay-sdk-rust/311697521ee9f7e3cdd721de13c16ff9a07a7c6d/CHANGELOG.md

### Expected behavior 🤔

Expected behavior would be valid links to commits written to the changelog.

### Steps to reproduce 🕹

It should be possible to reproduce this in any repository with a remote of `git@github.com:<user>/<repo>`.

**Comment by Byron** [comment]
> I've been using cargo-smart-release for months now and just noticed today that the links to commits in the generated changelog are invalid

That's awesome, and great catch, thanks for creating such a detailed report!

I couldn't resist to take a look at exactly where you pointed me and the fix was just one (previously missing) unit test away. Another `cargo smart-release cargo-smart-release -e` later and all [was set and done](https://github.com/Byron/gitoxide/releases/tag/cargo-smart-release-v0.12.0).

Next time you release I would expect the changelogs in the repository to be rewritten with the correct links. The annotated tags and GitHub releases will remain like this forever though.

**Comment by mattcl** [comment]
Can confirm the fix works for me. Thanks for the quick turnaround.
