### ISSUE TITLE
Regular Repositories can't be opened on macOS exFAT

### ISSUE THREAD

**Issue by davidkna** [Byron/gitoxide#514]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Repositories can't be opened on macOS exFAT Volumes. (starship/starship#4316)

Despite encountering a `.git` (directory) `File::open` succeeds, leading to the code path for opening `.git` files instead of directories. It contains file system data which cannot pass gitfile validation or could be rejected for size reasons.

### Expected behavior 🤔

Repository works on macOS exFAT

### Steps to reproduce 🕹

1. Try to open a git repository on a macOS exFAT Volume via `git_repository::open`

**Comment by davidkna** [comment]
I've pushed a preliminary fix here, but I haven't figured out how to properly test it yet: https://github.com/davidkna/gitoxide/tree/macos-exfat

**Comment by Byron** [comment]
Thanks for letting me know!

I still remember that I wanted to save IOPs by relying on the file system to tell what's up, just to now learn this behaviour is file-system dependent. Too bad :/.

I think the fix is adequate and a PR for it would be appreciate all on its own. In case you want to see if a test is possible, and if you are on MacOS, [this test might serve as example](https://github.com/Byron/gitoxide/blob/1b0ef1856f542e5dc23310be93c2b39a9d84cb80/git-discover/tests/upwards/mod.rs#L188) on how to create a temporary filesystem. If not, I am happy to give it a shot by pushing into the PR you could create. Thank you.
