### ISSUE TITLE
Provide a pure-Rust alternative to the blocking libcurl HTTP backend

### ISSUE THREAD

**Issue by jhp0tter** [Byron/gitoxide#530]
### Summary 💡

Hi,

I'm not familiar with the inner workings of Git, but it seems that it would be better if curl were to be replaced with a native Rust HTTP client (e.g. `hyper` or `ureq`) as the implementation of the blocking HTTP client in `git-transport`?

I'd be willing to work on this if this is something that is desired.

**Comment by Byron** [comment]
Learning about the motivation would indeed be interesting, but in it's absence I think an async http(s) implementation would be of greater value as currently there is none at all.

That said, if you would like to provide an alternative implementation backed by a pure-Rust implementation, I certainly would appreciate a PR as well. Note that it wouldn't replace the curl backend, but be an alternative.

**Comment by Byron** [comment]
Note that I have adjusted the title of this issue accordingly as it can stand only in this form, please feel free to close it if that goes against the original motivation.

**Comment by Shnatsel** [comment]
I'm looking to convert [`cargo audit`](https://crates.io/crates/cargo-audit), and we need it for these reasons:

1. Use `rustls` as the TLS implementation instead of memory-unsafe OpenSSL required by curl (which keeps getting CVEs)
1. Use memory-safe code to interface with the network (again, CVEs)

Clients that don't rely on async Rust internally (e.g. ureq, attohttpc) are preferred over those that do use async (`reqwest`, etc) but that's not as strong of a requirement.

**Comment by Byron** [comment]
I had forgotten about this issue and am happy to say that an initial implementation of a blocking transport via `reqwest` is already available.

It can be used in your `Cargo.toml` like so:

```toml
git-repository = { version = "^0.25.0", features = ["blocking-network-client"] }
git-transport-for-configuration-only = { version = "^0.21.0", package = "git-transport", features = ["http-client-reqwest"] }
```

This way fetches and clones handled by `git-repository` will automatically use the `reqwest` for all `http(s)` transports.

Closing as I think this issue is fulfilled.
