### ISSUE TITLE
git-diff, Tree, TreeRef, TreeRefIter

### ISSUE THREAD

**Issue by xmo-odoo** [Byron/gitoxide#557]
### Summary 💡

`git_diff::tree::Changes` works off of `TreeRefIter`, but when we have a `Tree` or `TreeRef` there's no way to get a `TreeRefIter` out of either, despite the ability to get an iterator of respectively Entry and EntryRef.

It would be nice if:
- `tree::Entry` could be converted to an `EntryRef`
- `Changes` could work off of arbitrary `EntryRef` iterators, not just `TreeRefIter` specifically

### Motivation 🔦

The current interface works great if the store interface provides borrowed access to the stored blob, but sometimes it's not the most convenient and the store returning validated and converted objects is easier on the rest of the code, even if it might be less efficient (e.g. for test cases or test harnesses).

The current limitations seem unfortunate, as it doesn't seem like this is a capabilities thing.

**Comment by Byron** [comment]
Thanks for bringing this up and the clear description - I totally understand.

Unfortunately, the way I see it being generic over `Iterator<Item = EntryRef>` would force the implementation to use `Box<dyn Iterator…>` internally which forces an allocation each time a new tree (for the source side) is acquired. The alternative would be an `Either` like enum that is representing the initial root tree exactly once, adding considerable complexity.

Since this is a plumbing crate, I am OK with the requirement of passing in exactly what it needs, and would rather work towards making its use unnecessary.

Ideally one can use facilities provided directly by `git-repository` instead.

I am closing this issue as the original suggestion (the points below `It would be nice if`) aren't feasible. 

But, I'd also like to understand more in the comments here and see why it's not possible to use the higher-level [`diff-api`](https://github.com/Byron/gitoxide/blob/53acf2565743eff7cead7a42011107b2fc8d7e0e/git-repository/src/object/tree/diff.rs#L95). I'd hope to make it work for your use-case once that is better understood.
Thank you.

**Comment by Byron** [comment]
> As such, the low-level gitoxide crates have been absolute god-sends.

That's great to hear! It seems because of direct usage of plumbing crates, the higher-level `diff` API isn't feasible for you?
Originally I was thinking that even I myself would rather use plumbing crates for ultimate control and maximum performance, but soon realized that it's possible to get comfort _and_ performance at the same time while shaping up `git-repository`. Since then it became clear to me that the server should use `git-repository` and resort to plumbing only when benchmarks suggest there is a win that pays for the added complexity.

The more I understand your use-case the higher the chances `git-repository` can become what you need. Please note that it's on the roadmap to have a server powered by `gitoxide` as well, but it will take some time to get there. Since you seem to be there already, I consider this  an opportunity to learn.

**Comment by xmo-odoo** [comment]
> > As such, the low-level gitoxide crates have been absolute god-sends.
> 
> That's great to hear! It seems because of direct usage of plumbing crates, the higher-level `diff` API isn't feasible for you? 

Not sure which `diff` you mean, the one from `git-repository`? `git-diff` works, it's just that as I changed the store implementation so borrowing was more complicated, which made me try out the owned APIs (which I understand are mostly for creation purposes but there you go), and find out Changes was not compatible with that.

> Originally I was thinking that even I myself would rather use plumbing crates for ultimate control and maximum performance, but soon realized that it's possible to get comfort _and_ performance at the same time while shaping up `git-repository`. Since then it became clear to me that the server should use `git-repository` and resort to plumbing only when benchmarks suggest there is a win that pays for the added complexity.
> 
> The more I understand your use-case the higher the chances `git-repository` can become what you need. Please note that it's on the roadmap to have a server powered by `gitoxide` as well, but it will take some time to get there. Since you seem to be there already, I consider this an opportunity to learn.

It's possible, I've started a while ago (I apparently posted my first interaction in October 2021) so it's possible that:

- I focused too much on the low-level sub-crates and missed the forest for the trees
- I didn't see a way to do what I needed with the high-level sub-crates

Frankly, by and large I've been really happy with the low-level sub-crates, they've mostly been helpful and fun.

**Comment by Byron** [comment]
> Not sure which diff you mean, the one from git-repository?

I mean [the `git-repository` diff implementation](https://github.com/Byron/gitoxide/blob/53acf2565743eff7cead7a42011107b2fc8d7e0e/git-repository/src/object/tree/diff.rs#L95), but it looks like you don't use `git-repository`.

> Frankly, by and large I've been really happy with the low-level sub-crates, they've mostly been helpful and fun.

Good to hear! On the server it's probably alright as well due to having much more control over where it runs and what it does. Plumbing crates need manual configuration and don't use `git-config`, making them less useful (if correctness is a concern) in client side repositories.
