### ISSUE TITLE
Set rust-version in Cargo.tomls

### ISSUE THREAD

**Issue by passcod** [Byron/gitoxide#691]
### Summary 💡

It would be nice if the MSRV was set in Cargo.tomls for the crates so cargo could make use of it / report on it, instead of just being "stealth" in the clippy config

### Motivation 🔦

My builds broke recently as I try to guarantee a wider MSRV (so crates are buildable on distro rust) (currently to 1.61) and the git-features crate started using new-as-of-1.64 boolean `.then_some()` methods, as introduced in #690.

This is just a nicety to get a warning early and avoid hunting down exactly what version is needed and which crate version to lock back to; [currently](https://github.com/rust-lang/cargo/issues/9930) rust-version isn't used in resolution.

**Comment by Byron** [comment]
Thanks for bringing this up.

I will add the MSRV of the project to all crates to resolve this. Being more granular isn't in scope I think without loosing my sanity 😅.

When done, not only the `git-repository` crate will specify their `rust-version`, but all of them.

Please note that I consider an MSRV change to be breaking for now and I would have hoped I specified it that way. But maybe, this time I failed to do this so it would sneak in this breaking change, sorry for that.

In future, thanks to the `rust-version` being present in each crate, that shouldn't happen anymore - because of the field, and because it's marked as a breaking change.
