### ISSUE TITLE
`git-discover` doesn't allow extended-length paths on Windows as ceiling directories

### ISSUE THREAD

**Issue by Nerixyz** [Byron/gitoxide#730]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Adding a ceiling directory with an extended-length path results in the directory being ignored when discovering upwards from a path that _doesn't_ use the extended-length path syntax. An extended-length path is a path prefixed with `\\?\` this is e.g. used in [`std::fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) (Windows docs: [Naming a file](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file), [Maximum Path Length Limitation](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation)).

### Expected behavior 🤔

The ceiling directory should be picked up regardless of which path syntax is used (this is the case for the regular git executable).

### Steps to reproduce 🕹

I created a test program that should run successfully, assuming the following directory layout:

```
directory-with-git-repo/
├─ .git
╰─ some/
   ╰─ child/
      ╰─ dir/ <- cwd
```

```rust
use git_discover::{upwards::Options, upwards_opts};

fn main() {
    let cwd = std::env::current_dir().unwrap();
    let parent = cwd.parent().unwrap();
    // all discoveries should fail, as they'll hit `parent` before finding a git repository.

    // dir: normal, ceiling: normal
    let r1 = upwards_opts(
        &cwd,
        Options {
            ceiling_dirs: vec![parent.to_path_buf()],
            match_ceiling_dir_or_error: false,
            ..Default::default()
        },
    );

    let parent = parent.canonicalize().unwrap();
    // dir: normal, ceiling: extended
    let r2 = upwards_opts(
        &cwd,
        Options {
            ceiling_dirs: vec![parent],
            match_ceiling_dir_or_error: false,
            ..Default::default()
        },
    );

    let cwd = cwd.canonicalize().unwrap();

    let parent = cwd.parent().unwrap();
    // dir: extended, ceiling: normal
    let r3 = upwards_opts(
        &cwd,
        Options {
            ceiling_dirs: vec![parent.to_path_buf()],
            match_ceiling_dir_or_error: false,
            ..Default::default()
        },
    );

    let parent = parent.canonicalize().unwrap();
    // dir: extended, ceiling: extended
    let r4 = upwards_opts(
        &cwd,
        Options {
            ceiling_dirs: vec![parent],
            match_ceiling_dir_or_error: false,
            ..Default::default()
        },
    );

    assert!(matches!(
        dbg!((r1, r2, r3, r4)),
        (Err(_), Err(_), Err(_), Err(_))
    ));
}
```

This should run on all platforms. Currently, on Windows, `r2` (the case I described above) will be `Ok(_)` (meaning a git repository was discovered). This is wrong.

It seems like [`Path::strip_prefix`](https://doc.rust-lang.org/std/path/struct.Path.html#method.strip_prefix) doesn't strip the prefix when `\\?\` is used in the prefix ([used here](https://github.com/Byron/gitoxide/blob/9e7d79273487abfcb99ed2d439c475a659cd25e6/git-discover/src/upwards/util.rs#L56)).

**Comment by davidkna** [comment]
@Nerixyz In starship please just use `dunce`.

**Comment by Byron** [comment]
Thanks so much for reporting the issue and for providing a program that can probably be turned into a test as well.

I have a feeling that not even git supports UNC paths in `GIT_CEILING_DIR` - is this something you could test and share here for curiosity sake?

It seems like `gitoxide` should use `dunce` to cleanup paths it obtains from environment variables by default in order to assure the downstream functions properly.

**Comment by davidkna** [comment]
@Byron `dunce` converts the path into a string to strip the prefix, so it may not be ideal. Doesn't gitoxide already come with its own path normalization functions?
Additionally, AFAIK verbatim paths live in a different namespace compared to regular paths, and have additional restrictions, thus I'm not sure if handling them alike is appropriate.

**Comment by Byron** [comment]
> @Byron dunce converts the path into a string to strip the prefix, so it may not be ideal. Doesn't gitoxide already come with its own path normalization functions?

Indeed it does, and they are used extensively as well. I think it could absolutely be a next step to use `dunce` in there to make cases like these work. For now, the implementation is very specific to cover only this case though, and it uses `dunce` knowing that it might not be able to handle paths due to the `to_str()` conversion.

The next step could indeed mean to integrate dunce into the normalization functions that are already available, but that seemed like more work for now especially since testing is more cumbersome.

Please let me know what you think - sometimes it just takes a little kick to go the extra, extra mile.
