### ISSUE TITLE
.git/HEAD is missing a newline

### ISSUE THREAD

**Issue by vincentdephily** [Byron/gitoxide#836]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Running `gix clone <somerepo>` creates a `.git/HEAD` file containing just `ref: refs/heads/main` (no newline). Running the same command with `git` creates the file with the same content plus a newline.

This seems like a cosmetic difference, but it affects at least the bash prompt distributed by git in `/usr/share/git/git-prompt.sh`: without the newline, `__git_ps1()` return an empty string instead of the repo info. You might argue this is a git bug, but I am afraid other tools might be affected.

### Steps to reproduce 🕹

1. bash
2. source /usr/share/git/git-prompt.sh
3. export PS1='$(__git_ps1) \$'
4. git clone git@github.com/foo/bar bargit
5. gix clone git@github.com/foo/bar bargix
6. cd bargit # -> bash prompt is ok
7. cd ../bargix # -> bash prompt finds nothing
8. echo >> .git/HEAD # -> bash prompt now works

The repo I cloned has a single branch. That may affect behaviour. 
Using gitoxide-0.25.0 and git-2.39.0.

**Comment by Byron** [comment]
Thanks a million!

I won't argue about that as it definitely is a subtlety that `gitoxide` should be handling correctly.
After investigating I appear to have found out that `git` practically adds a newline when writing symbolic refs, whether it's HEAD or something created with `git symbolic-ref`. 

Thus I believe this can be fixed by updating `git-ref` directly, and when fixed I will create a new patch release for it.

**Comment by Byron** [comment]
The fix [should now be available](https://github.com/Byron/gitoxide/releases/tag/gix-ref-v0.29.1) when using the latest `gix`.
