### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by advokat11** [Byron/gitoxide#922]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

```
 14:52:13 read pack done 1.7MB in 0.42s (4.1MB/s)
 14:52:13  indexing done 4.5k objects in 0.31s (14.5k objects/s)
 14:52:13 decompressing done 3.7MB in 0.31s (11.9MB/s)
thread ' gitoxide.in_parallel.produce.1anicked at '2not yet implemented;', 43C:\Users\user\temp\gitoxide\gix-worktree\src\checkout\entry.rs;:37103m:14:52:1343      2 of 4 steps [===============>---------------------------------------------]
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace========================================>]
    Resolving hread '1main;' panicked at '37a scoped thread panickedm', done 4.5k objects in 0.13s (35.3k objects/s)C:\Users\user\temp\gitoxide\gix-features\src\parallel\in_parallel.rs: 62 : 5

 14:52:13      Decoding done 19.3MB in 0.13s (150.1MB/s)
 14:52:13 writing index file done 128.0KB in 0.00s (249.0MB/s)
 14:52:13  create index file done 4.5k objects in 0.44s (10.3k objects/s)
```

### Expected behavior 🤔

The repository must be cloned

### Steps to reproduce 🕹

1. Install windows 10 19044.1288
2. Build gitex via rust nightly
3. Type command: "gix clone https://github.com/rpgp/rpgp.git"

**Comment by Byron** [comment]
Submodules are currently unsupported and [the code indicates that](https://github.com/Byron/gitoxide/blob/5d2b5d02c3869e07dc2507a8f2519ee1df633df7/gix-worktree/src/checkout/entry.rs#L102-L103) by causing a panic.

You can follow the progress on performing complete checkouts [in the tracking issue](https://github.com/Byron/gitoxide/issues/301). Closing, as this issue is known and 'intended', thanks for your understanding.
