### ISSUE TITLE
Allow optional updating of symbolic references when fetching

### ISSUE THREAD

**Issue by Jake-Shadle** [Byron/gitoxide#926]
### Summary 💡

When doing a [fetch](https://docs.rs/gix/0.48.0/gix/remote/fetch/struct.Prepare.html#method.receive) it would be very handy to have an API, either as part of [`prepare`](https://docs.rs/gix/0.48.0/gix/remote/struct.Connection.html#method.prepare_fetch) or an additional post-fetch method like [`fetch_then_checkout`](https://docs.rs/gix/0.48.0/gix/clone/struct.PrepareFetch.html#method.fetch_then_checkout) (but notably, _not_ tied directly to checkout) that could be used to update symbolic references.

### Motivation 🔦

Currently when fetching, [`update_refs::update`](https://github.com/Byron/gitoxide/blob/c3ee57b9d71f650784dc0a5022dbf54fe71e5fe5/gix/src/remote/connection/fetch/update_refs/mod.rs#L46) is called to...update references. However, , if the reference is [symbolic](https://github.com/Byron/gitoxide/blob/c3ee57b9d71f650784dc0a5022dbf54fe71e5fe5/gix/src/remote/connection/fetch/update_refs/mod.rs#L105-L108) it is not updated. This makes sense as a default so that doing a simple fetch doesn't mutate the local references, but it does mean if the user _does_ want to update a symbolic reference, a typical case being `HEAD:refs/remotes/origin/HEAD`, then they have to essentially [duplicate](https://github.com/EmbarkStudios/tame-index/blob/main/src/index/git_remote.rs#L195-L264) a large portion of the logic to "manually" update the symbolic reference after a fetch.

This request is mainly focused on the use case of bare repositories that are not (usually) directly interacted with by users where the local `HEAD` is not really relevant but more the remote `HEAD`. However, the current [`Head`](https://docs.rs/gix/0.48.0/gix/struct.Head.html) API is really convenient to use, hence the desire to be able to update the `HEAD` to point to the same peeled commit as the remote `HEAD`.

**Comment by Byron** [comment]
Thanks for the hint, I will definitely take a look soonish!

If I understood `git` correctly, it really tries hard not to touch `HEAD`, and maybe the current `gitoxide` implementation is too broad to completely prohibit it. This might be a bug and I will see if that can just be enabled (except for setting `HEAD`), or if that should be configurable instead.

**Comment by Byron** [comment]
This will be improved with the next release, I will post here when that happens and it should be today or tomorrow - I am working on it.

It turns out that I definitely took a shortcut by simply not handling symbolic refs, which do complicate things quite a bit, but since some time passed I will it's a good time to tackle.
When using `gix fetch` I also noticed that it would refuse to do anything with `origin/HEAD` and thought that was unnecessary.

The new logic will happily update any refs, symbolic or not, if…

* fast-forward rules aren't violated
* if the target ref is not currently checked out

That should really be all that matters.

**Comment by Jake-Shadle** [comment]
Yup I think those two constraints make total sense as they (probably) won't affect the use case of updating a bare repository since those tend to be managed via code rather than manually by a user, so this change would effectively give the same benefits as fetch + checkout but for bare repositories.

**Comment by Byron** [comment]
This will be fixed with the next release, I will post here when that happens. Figuring this out was quite some work, but as always, that is rewarded. Now I think the logic is finally sound and more tested, too, which should allow `gix` to mirror repos pretty nicely.

I added a third rule to the above, repeated here for completeness:

---
The new logic will happily update any refs, symbolic or not, if…

* fast-forward rules aren't violated
* the target ref is not currently checked out
* *existing refs would not become 'unborn', i.e. point to a reference that doesn't exist and won't be created due to ref-specs*
---
