### ISSUE TITLE
Filtering protocol features

### ISSUE THREAD

**Issue by FintanH** [Byron/gitoxide#928]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

I am attempting to pass some feature capabilities from a client-side using gitoxide to a server that is running upload-pack. For example,  I would like to see what happens when I pass [`no-progress`](https://git-scm.com/docs/protocol-capabilities/2.28.0#_no_progress). At the moment, I'm attempting to do this by pushing the feature and running the `send` on the `Arguments`, e.g.:

```rust
features.push(("no-progress", None));
let mut args = fetch::Arguments::new(*protocol, features);

/* negotiation loop */
let mut reader = args.send(&mut conn, action == fetch::Action::Cancel)?;
```

I never see this capability being received by the server side, and I noticed this line of code is filtering any values that are `None` https://github.com/Byron/gitoxide/blob/main/gix-protocol/src/fetch/arguments/blocking_io.rs#L50.

### Expected behavior 🤔

I believe that if I use the code above with:
```rust
features.push(("no-progress", None));
```

that the capability would be advertised, but perhaps I'm using it incorrectly?

### Steps to reproduce 🕹

Sorry, I don't have any reproducible steps.

**Comment by Byron** [comment]
Thanks for reporting!

To me seems a little unclear right now why it performs such filtering in the first place. Maybe removing it wouldn't cause any test failures that then help to shed some light?

Since you already found the spot and if you have a moment, I'd definitely welcome a PR with a fix.
Otherwise I will definitely investigate, but it won't be instantaneous.

**Comment by FintanH** [comment]
Thanks @Byron :)

> To me seems a little unclear right now why it performs such filtering in the first place

I was curious about this myself. I played around a bit but came to no substantial conclusions. I ended up realising that I was holding the `Progress` trait wrong so that solved my particular problem -- classic XY question on my behalf.

I'd be more than happy to look at specific gitoxide tests if you could point me in a particular direction. But thankfully, no urgency on my end now :)

**Comment by Byron** [comment]
> I was curious about this myself. I played around a bit but came to no substantial conclusions. I ended up realising that I was holding the Progress trait wrong so that solved my particular problem -- classic XY question on my behalf.

That's great, and I am glad you didn't have to disable progress entirely given the time it usually takes to do fetches.

> I'd be more than happy to look at specific gitoxide tests if you could point me in a particular direction. But thankfully, no urgency on my end now :).

I would have remove the filter line in question and run all tests. Ideally, one or more would fail whose context then provide hints at why this filtering was deemed necessary.

**Comment by Byron** [comment]
I have taken a closer look and realize now that `"no-progress"`, once available as feature, has to be added to the list of arguments, rather than be used as a feature, at least that's [what I gather from the docs](https://github.com/git/git/blob/ee48e70a829d1fa2da82f14787051ad8e7c45b71/Documentation/gitprotocol-v2.txt#L277).
This means it has to be added to `Arguments::args` and that is only available through specific methods. In other words, support would have to be added specifically.
Umm, never mind, it turns out that there are plenty of additional 'features' that are supposed to be arguments as per documentation, but definitely are not in practice.

It really looks like the way features are handled is 'fitted' into something that works in practice, and it's pushed into place so that typical arguments and features are naturally added just in the right place with more special cases that I'd like.

With all that said, It *should* be possible to remove that filtering, which seems to exist so that `shallow` isn't sent to the server as capability (as it fails then). Maybe doing this will allow this and other use-cases, without adding yet another special case 😅.

**Comment by Byron** [comment]
This issue should be resolved with [the latest release](https://github.com/Byron/gitoxide/releases/tag/gix-v0.51.0), but please let me know if anything is missing. Thanks.
