### ISSUE TITLE
Spurious illegal instructioin on x86_64-unkown-linux-musl

### ISSUE THREAD

**Issue by NobodyXu** [Byron/gitoxide#955]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

`cargo-binstall`, which uses `gix` v0.50.1, sometimes get killed by illegal instructions on [this CI](https://github.com/cargo-bins/cargo-binstall/actions/runs/5689917580/job/15422302958#step:11:157) and also [this one](https://github.com/cargo-bins/cargo-binstall/actions/runs/5722259457/job/15505050290#step:11:158):

```
+ ./cargo-binstall binstall --force --git file:///tmp/tmp.iyk2axDWcq --no-confirm cargo-binstall
 INFO resolve: Resolving package: 'cargo-binstall'
 INFO Cloning::receiving pack: Enumerating objects → 3.0 objects
git.sh: line 39: 24033 Illegal instruction     (core dumped) "./$1" binstall --force --git "file://$GIT" --no-confirm cargo-binstall
```

I suspect this has something to do with `max-performance`, it could be that the use of assemblies in `sha1-asm` or `libz-ng` caused this problem.

It always happens when cloning from a local git repository using `file:///`, so I suppose it also has something to do with it.

**Comment by NobodyXu** [comment]
Oops it just [happens again](https://github.com/cargo-bins/cargo-binstall/actions/runs/5723557176/job/15508357940?pr=1231#step:11:160)

**Comment by NobodyXu** [comment]
It also [happens](https://github.com/cargo-bins/cargo-binstall/actions/runs/5723607133/job/15508519105?pr=1234#step:12:7524) on `x86_64-unknown-linux-gnu`.

**Comment by Byron** [comment]
That's interesting as it doesn't reproduce (or is nothing I encountered) in this CI yet. Thus another possible cause may be be miscompilation, in addition to assembly as potential cause.

If the issue is miscompilation, then adding ` rustflags = ["-Ctarget-cpu=native"]` (or removing it) might affect codegen and maybe resolves the issue that way.

If assembly is the issue, you could try to disable one or the other performance option, using either `sha1-asm` only or only `libz-ng` (or another zlib implementation for that matter). To do that, you would go with `max-performance-safe`, add a dependency to `gix-features` and add `--features = ["fast-sha1"]` *or* `--features = ["zlib-ng"]` (or another backend) to see issue is fixed that way.

Please note that I *think* for performance, a great `zlib` implementation is more important than a great hash implementation,  even though I didn't yet run tests to validate my hunch (as a disclaimer).

Thanks for letting me know how it goes.

PS: Maybe another possible issue is some strange interaction with the VM this runs on. After all, illegal instructions *should* always be run in tight algorithms like SHA1 or zlib-ng, so it should consistently crash. But it doesn't, so might be related to something else entirely. In any case, changing the instructions in the binary might help to fix it merely by not using the maybe special instructions that come with assembly or certain super-optimized C code in zlib-ng.

**Comment by NobodyXu** [comment]
Thanks for the swift response!

I will disable `sha1-asm` and leaving only `zlib-ng`, since IMO `zlib-ng` is more battle-tested and it provides more speedup than `sha1-asm`.

**Comment by NobodyXu** [comment]
@Byron I tried disabling `sha1-asm` but the [failure persists](https://github.com/cargo-bins/cargo-binstall/actions/runs/5725773404/job/15514915194#step:11:160)

**Comment by Byron** [comment]
That's great, as one possibility has been removed. The next to try would be zlib-ng then (while leaving sha1-asm disabled)? Maybe change it to the normal backend to retain *some* performance. If that still doesn't work, try with `max-performance-safe` alone, that is pure Rust then.

**Comment by NobodyXu** [comment]
Yeah, after I disabled `zlib-ng` for `x86_64-unknown-linux-{gnu, musl}`, it no longer happens.

I guess we should report this to upstream.

**Comment by NobodyXu** [comment]
After `zlib-ng` and `sha1-asm` is disabled, the time for cloning crates.io git-index [increases a lot](https://github.com/cargo-bins/cargo-binstall/actions/runs/5725969116/job/15515507944?pr=1236#step:11:18135) but is still reasonable since we no longer checkout the repository now.

**Comment by Byron** [comment]
Great to hear we pin-pointed it! I recommend turning `sha1-asm` back on to get a little performance back. If the issue reoccurs than we'd also learn something, i.e. it would then be some combination of libraries or some strangeness with codegen maybe.

For now I am tentatively closing this issue as there is nothing we can do here, and follow the related issue instead.
If something changes, this issue should be reopened though.

**Comment by NobodyXu** [comment]
> Great to hear we pin-pointed it! I recommend turning `sha1-asm` back on to get a little performance back.

I think the current performance is already good enough, in fact I believe that as long as we don't do a checkout, it will be ok for binstall to even switch back to -Oz.

If the performance becomes a problem again, binstall can employ the same caching schema used in `.cargo/registry/index`, although I'm not sure how `cargo` determines the name of the directory and prevent concurrent access to it.

**Comment by Byron** [comment]
> If the performance becomes a problem again, binstall can employ the same caching schema used in .cargo/registry/index, although I'm not sure how cargo determines the name of the directory and prevent concurrent access to it.

You might be interested in `tame-index` or `crates-index` - they make it possible to use the local cargo caches, even though I think `tame-index` might be better for that as it's better organized.

**Comment by NobodyXu** [comment]
> You might be interested in `tame-index` or `crates-index` - they make it possible to use the local cargo caches, even though I think `tame-index` might be better for that as it's better organized.

Thanks!

Although I am still a bit hesitant on pulling them, since binstall used to depend on it but was explicitly removed because its dependence on `curl` and `openssl` making the final binary much harder to redistribute.

If binstall needs this, I might port this code from `crates-index` to our crate, although I'm not sure how to use `gix` to update an existing repository shallowly.

**Comment by Byron** [comment]
> Although I am still a bit hesitant on pulling them, since binstall used to depend on it but was explicitly removed because its dependence on `curl` and `openssl` making the final binary much harder to redistribute.

`crates-index` and `tame-index` both use `gix`, so it's possible to configure it without. `tame-index` in particular makes it easy to avoid dependencies, I think, and use the cache directly or write it. That would be my first choice, and I am saying that as the (albeit freshly made) maintainer of `crates-index`.

> [..]  although I'm not sure how to use gix to update an existing repository shallowly.

`gix` does the right thing by default and no configuration is needed to maintain shallowness. Otherwise it can be controlled [here](https://docs.rs/gix/0.50.1/gix/clone/struct.PrepareFetch.html#method.with_shallow).

**Comment by NobodyXu** [comment]
> `crates-index` and `tame-index` both use `gix`, so it's possible to configure it without. `tame-index` in particular makes it easy to avoid dependencies, I think, and use the cache directly or write it. That would be my first choice, and I am saying that as the (albeit freshly made) maintainer of `crates-index`.

Thanks, I would take note of this in case we need this feature in binstall.

> `gix` does the right thing by default and no configuration is needed to maintain shallowness. Otherwise it can be controlled [here](https://docs.rs/gix/0.50.1/gix/clone/struct.PrepareFetch.html#method.with_shallow).

I actually don't know how to update a cloned repository in `gix`, although based on your reply it seems like I just need to provide it with the existing paths and it would work.

**Comment by Byron** [comment]
> I actually don't know how to update a cloned repository in `gix`, although based on your reply it seems like I just need to provide it with the existing paths and it would work.

Fetching works by [using a remote](https://github.com/Byron/gitoxide/blob/df810766dfeaaad7474339358a3d844b2c3368cd/gitoxide-core/src/repository/fetch.rs#L61-L66) and is quite straightforward.

**Comment by NobodyXu** [comment]
> Fetching works by [using a remote](https://github.com/Byron/gitoxide/blob/df810766dfeaaad7474339358a3d844b2c3368cd/gitoxide-core/src/repository/fetch.rs#L61-L66) and is quite straightforward.

Thanks!

I will also take note of this.
