### ISSUE TITLE
When using `rustls`, allow using `rustls-native-tls` instead of `webpki-roots`

### ISSUE THREAD

**Issue by Shnatsel** [Byron/gitoxide#991]
### Summary 💡

Right now when using `reqwest` with `rustls`, gix uses the `rustls-tls` feature of `reqwest`. This is an [alias](https://github.com/seanmonstar/reqwest/blob/1f6c2cfcf9315a9721314171568a41beebf5b311/Cargo.toml#L41C1-L41C11) for `rustls-tls-webpki-roots` feature, which uses [`webpki-roots`](https://crates.io/crates/webpki-roots) package to provide the list of trusted HTTPS certificates.

The alternative to `webpki-roots` is the [`rustls-native-certs`](https://crates.io/crates/rustls-native-certs) package. Its README does a good job listing the pros and cons of each approach.

`reqwest` allows using `rustls-native-tls` via the `rustls-tls-native-roots` Cargo feature, but it is not exposed by the `gix` crate.

Fixing this should be as easy as adding another Cargo feature to `gix` that activates the `rustls-tls-native-roots` feature on `reqwest` crate instead of  `rustls-tls` feature.

### Motivation 🔦

We need to use the native certificate store in `cargo audit`.

The primary reason is that it is required in certain enterprise environments where the enterprise "firewalls" (actually surveillance machines) intercept all HTTPS traffic. In such an environment it is impossible to contact the outside world without using the OS's certificate store.

**Comment by Byron** [comment]
Is there a reason the [`blocking-http-transport-reqwest-native-tls`](https://github.com/Byron/gitoxide/blob/e5717e1d12c49285d31a90b03b7f8e9cbc6c1108/gix/Cargo.toml#L50-L51) can't be used in conjunction with referring to [a configuration crate](https://github.com/Byron/gitoxide/blob/e5717e1d12c49285d31a90b03b7f8e9cbc6c1108/gix/Cargo.toml#L194) for the sole purpose of activating the `rustls-tls-native-roots`?

I am saying this because to me the provided feature toggles for reqwest are for convenience only without the intend to forward all of the them to satisfy every possible need. Instead I find it more feasible both for `gix` as well as for users of `gix` to pull in certain crates, like `gix-features` or `reqwest` just to configure feature toggles. 

Today I learned that with cargo-deny it's also possible to [prevent the usage crates above or below a certain version](https://github.com/Byron/gitoxide/pull/993/files#diff-1040309c64844eb1b6b63d8fd67938adbf9461f1b3c61f12cf738f064a02d3deR69), so this could be used to prevent `reqwest 2.0` silently be introduced by `gix` which would make the configuration crate useless.

Is this feasible for you as a general approach?

If not, I am happy to add that one feature toggle as well, it's `cargo audit` after all :).

**Comment by Shnatsel** [comment]
The approach to configuration you suggest sounds good! I've opened https://github.com/EmbarkStudios/tame-index/pull/15 to apply it to `tame-index` crate. Let's see if there are any concerns raised by the maintainer.

**Comment by Shnatsel** [comment]
The `tame-index` change is merged, and seems to work well. Closing. Thanks!
